# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#

include:
  - board: nice_nano_v2
    shield: klor_left
  - board: nice_nano_v2
    shield: klor_right

# wireless with dongle
  - board: nice_nano_v2
    shield: klor_left
    keymap: qwerty
    format: dongle
    artifact-name: klor_qwerty_dongle_left
  - board: nice_nano_v2
    shield: klor_right
    keymap: qwerty
    format: dongle
    artifact-name: klor_qwerty_dongle_right
  - board: seeeduino_xiao_ble
    keymap: qwerty
    format: dongle
    shield: klor_dongle dongle_screen
    artifact-name: totem_qwerty_dongle_yads

 # Firmware Reset
  - board: seeeduino_xiao_ble
    shield: settings_reset
    format: reset
    artifact-name: firmware_reset_dongle
  - board: nice_nano_v2
    shield: settings_reset
    format: reset
    artifact-name: firmware_reset_klor
